/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSponsorshipRouteImport } from './routes/_site.sponsorship'
import { Route as SiteProductsRouteImport } from './routes/_site.products'
import { Route as SitePartnersRouteImport } from './routes/_site.partners'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteClaimsRouteImport } from './routes/_site.claims'
import { Route as SiteCareersRouteImport } from './routes/_site.careers'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSponsorshipRoute = SiteSponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SitePartnersRoute = SitePartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteClaimsRoute = SiteClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareersRoute = SiteCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/careers': typeof SiteCareersRoute
  '/claims': typeof SiteClaimsRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/partners': typeof SitePartnersRoute
  '/products': typeof SiteProductsRoute
  '/sponsorship': typeof SiteSponsorshipRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/careers': typeof SiteCareersRoute
  '/claims': typeof SiteClaimsRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/partners': typeof SitePartnersRoute
  '/products': typeof SiteProductsRoute
  '/sponsorship': typeof SiteSponsorshipRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/careers': typeof SiteCareersRoute
  '/_site/claims': typeof SiteClaimsRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/partners': typeof SitePartnersRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/sponsorship': typeof SiteSponsorshipRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/claims'
    | '/contact'
    | '/faq'
    | '/partners'
    | '/products'
    | '/sponsorship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/careers'
    | '/claims'
    | '/contact'
    | '/faq'
    | '/partners'
    | '/products'
    | '/sponsorship'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/careers'
    | '/_site/claims'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/partners'
    | '/_site/products'
    | '/_site/sponsorship'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sponsorship': {
      id: '/_site/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SiteSponsorshipRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/partners': {
      id: '/_site/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof SitePartnersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/claims': {
      id: '/_site/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof SiteClaimsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers': {
      id: '/_site/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof SiteCareersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCareersRoute: typeof SiteCareersRoute
  SiteClaimsRoute: typeof SiteClaimsRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePartnersRoute: typeof SitePartnersRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteSponsorshipRoute: typeof SiteSponsorshipRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCareersRoute: SiteCareersRoute,
  SiteClaimsRoute: SiteClaimsRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePartnersRoute: SitePartnersRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteSponsorshipRoute: SiteSponsorshipRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
